repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --frozen --cache-dir .uv-cache ruff check
        language: system
        files: ^(app|tests)/
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: ruff format --check
        entry: uv run --frozen --cache-dir .uv-cache ruff format --check
        language: system
        files: ^(app|tests)/
        types_or: [python, pyi]
        require_serial: true
